### PR TITLE
Add redirecturi

### PR DESCRIPTION
**Pull request by mmahalwy**
@parro-it i tried with postmessage but google has an endless `Connecting...` 

image

Might relate to: https://github.com/atom/electron/issues/1865

### CODE REVIEW

**Comment by parro-it** [comment]
I can't check it today, will do tomorrow. Meanwhile, have you checked in devtools network tab what's happening?

**Comment by mmahalwy** [comment]
@parro-it yep, nothing at all. It's like google is not responding

**Comment by parro-it** [comment]
if you use the default value of 'urn:ietf:wg:oauth:2.0:oob' does it works?

**Comment by parro-it** [comment]
If you look atom/electron/issues/4216 they are discussing this exact situation. This issue is merged with the one you mention.

**Comment by parro-it** [comment]
Anyway, tomorrow I'll merge your PR in favour of parro-it/electron-google-oauth/pull/3, maybe it solve @gotokatsuya use case too.
Thank you!

**Comment by mmahalwy** [comment]
Yep, but I think the problem is that google is not playing nice with electron when using `postmessage`

Not sure why.

**Comment by gotokatsuya** [comment]
Thank you guys! I close my PR :smile:

**Comment by parro-it** [comment]
Thank you @gotokatsuya

**Pull request merged**
