### PR TITLE
Fix Add redirectUri to arg

### PR DESCRIPTION
**Pull request by gotokatsuya**
Hi parro-it .

I want to use own redirect_uri.

### CODE REVIEW

**Comment by parro-it** [comment]
Hi, tank you for the PR :smile: 
Could you please add a default value for the new argument that make it get same value as before if not specified? This way, we can keep compatibility with old version...

**Comment by parro-it** [comment]
ping @gotokatsuya

**Comment by gotokatsuya** [comment]
@parro-it 

Sorry for delay reply.

OK !! Thank you !

**Comment by parro-it** [comment]
No worries! Take your time...

**Pull request closed without merging**
